# Generated by Django 3.2.23 on 2023-11-28 04:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0009_alter_livros_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='descricao',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='livros',
            name='data_cadastro',
            field=models.DateField(default=datetime.date(2023, 11, 28)),
        ),
    ]
