# Generated by Django 3.2.23 on 2023-12-12 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0011_auto_20231211_1823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprestimos',
            options={'verbose_name': 'Emprestimo'},
        ),
        migrations.RemoveField(
            model_name='emprestimos',
            name='tempo_duracao',
        ),
        migrations.AlterField(
            model_name='livros',
            name='data_cadastro',
            field=models.DateField(default=datetime.date(2023, 12, 12)),
        ),
    ]
