# Generated by Django 3.2.23 on 2023-12-29 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0015_auto_20231228_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 29, 11, 19, 35, 31507)),
        ),
        migrations.AlterField(
            model_name='livros',
            name='data_cadastro',
            field=models.DateField(default=datetime.date(2023, 12, 29)),
        ),
        migrations.AlterField(
            model_name='livros',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
