# Generated by Django 3.2.23 on 2023-12-30 21:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0016_auto_20231229_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimos',
            name='avaliacao',
        ),
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 30, 18, 25, 50, 57412)),
        ),
        migrations.AlterField(
            model_name='livros',
            name='data_cadastro',
            field=models.DateField(default=datetime.date(2023, 12, 30)),
        ),
        migrations.CreateModel(
            name='Avaliacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.CharField(blank=True, choices=[('P', 'Pessimo'), ('R', 'Ruim'), ('RL', 'Regular'), ('B', 'Bom'), ('O', 'Ótimo')], max_length=15, null=True)),
                ('livro_avaliado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='livro.livros')),
            ],
        ),
    ]
