# Generated by Django 3.2.23 on 2023-12-30 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0017_auto_20231230_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 30, 18, 26, 51, 957646)),
        ),
    ]
