# Generated by Django 3.2.23 on 2024-01-01 23:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0019_auto_20231230_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacoes',
            name='livro_avaliado',
        ),
        migrations.RemoveField(
            model_name='avaliacoes',
            name='usuario',
        ),
        migrations.AddField(
            model_name='avaliacoes',
            name='emprestimo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='livro.emprestimos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 1, 20, 46, 7, 5091)),
        ),
        migrations.AlterField(
            model_name='livros',
            name='data_cadastro',
            field=models.DateField(default=datetime.date(2024, 1, 1)),
        ),
    ]
