# Generated by Django 3.2.23 on 2024-01-02 00:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0020_auto_20240101_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimos',
            name='avaliacao',
            field=models.CharField(blank=True, choices=[('P', 'Pessimo'), ('R', 'Ruim'), ('RL', 'Regular'), ('B', 'Bom'), ('O', 'Ótimo')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 1, 21, 26, 58, 585750)),
        ),
        migrations.DeleteModel(
            name='Avaliacoes',
        ),
    ]
