# Generated by Django 3.2.23 on 2024-01-03 01:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0024_auto_20240102_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='data_publicacao',
            field=models.DateField(default=datetime.date(2024, 1, 2)),
        ),
        migrations.AddField(
            model_name='livros',
            name='edicao',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='livros',
            name='editora',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='livros',
            name='numero_paginas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 2, 22, 39, 55, 334835)),
        ),
    ]
