# Generated by Django 3.2.23 on 2024-01-03 03:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0025_auto_20240102_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 3, 0, 36, 29, 321701)),
        ),
        migrations.AlterField(
            model_name='livros',
            name='data_cadastro',
            field=models.DateField(default=datetime.date(2024, 1, 3)),
        ),
        migrations.AlterField(
            model_name='livros',
            name='data_publicacao',
            field=models.DateField(default=datetime.date(2024, 1, 3)),
        ),
    ]
