# Generated by Django 3.2.23 on 2024-01-04 01:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0028_auto_20240103_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 3, 22, 50, 12, 172867)),
        ),
        migrations.AlterField(
            model_name='livros',
            name='idioma',
            field=models.CharField(choices=[('PT-BR', 'Portugues-BR'), ('EN-US', 'Ingles (Estados Unidos)'), ('FR', 'Frances'), ('ES', 'Espanhol')], default='PT-BR', max_length=30),
        ),
    ]
