# Generated by Django 3.2.23 on 2024-01-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='avatar_usuario'),
        ),
    ]
